name       : ideviceinstaller
version    : 1.1.1
release    : 6
source     :
    - https://github.com/libimobiledevice/ideviceinstaller/releases/download/1.1.1/ideviceinstaller-1.1.1.tar.bz2 : deb883ec97f2f88115aab39f701b83c843e9f2b67fe02f5e00a9a7d6196c3063
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : ideviceinstaller is a tool to interact with the installation_proxy of an iOS device allowing to install, upgrade, uninstall, archive, restore and enumerate installed or archived apps.
description: |
    ideviceinstaller is a tool to interact with the installation_proxy of an iOS device allowing to install, upgrade, uninstall, archive, restore and enumerate installed or archived apps.
builddeps  :
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libzip)
    - bzip2-devel
setup      : |
    %reconfigure CFLAGS="$CFLAGS -Wno-error"
build      : |
    %make
install    : |
    %make_install
