name       : ideviceinstaller
version    : 1.1.0
release    : 1
source     :
    - http://www.libimobiledevice.org/downloads/ideviceinstaller-1.1.0.tar.bz2 : 0821b8d3ca6153d9bf82ceba2706f7bd0e3f07b90a138d79c2448e42362e2f53
license    : GPL-2.0
summary    : ideviceinstaller is a tool to interact with the installation_proxy of an iOS device allowing to install, upgrade, uninstall, archive, restore and enumerate installed or archived apps.
description: |
    ideviceinstaller is a tool to interact with the installation_proxy of an iOS device allowing to install, upgrade, uninstall, archive, restore and enumerate installed or archived apps.
builddeps  : 
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist)
    - pkgconfig(libzip)
setup      : |
    %configure CFLAGS="$CFLAGS -Wno-error"
build      : |
    %make
install    : |
    %make_install
